import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/walletProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black`}>
        <Providers>{children}</Providers>
        <Toaster
          toastOptions={{
            style: {
              wordBreak: "break-all",
              maxWidth: "350px",
              wordWrap: "normal",
            },
          }}
        />
      </body>
    </html>
  );
}
